### ISSUE TITLE
Missing importFrom(): Error in setClass("balance", ... : could not find function "setClass"

### ISSUE THREAD

**Issue by HenrikBengtsson** [suyusung/arm#12]
When running reverse package checks on {arm}, I'm getting:
```
    Error in setClass("balance", representation(rawdata = "data.frame", matched = "data.frame",  :
      could not find function "setClass"
```

Please add `"setClass"` to the list of imports from {methods} in the `NAMESPACE` file:

https://github.com/suyusung/arm/blob/7bbc274059c8d59486ef35a11e8877f0aac656a3/NAMESPACE#L23-L29

**Comment by suyusung** [comment]
Thx for the report.  Added and will be revealed in the next release.
