### ISSUE TITLE
How to get R squared in bayesglm?

### ISSUE THREAD

**Issue by yj-kim-00** [suyusung/arm#13]
Question 1. After deriving an estimate of the dependent variable (y) through the Bayesian multiple regression analysis Estimation Function (postf), the calculation of R squared is made using the cumulative sum function (cumsum). Is there no problem finding SSR(Sum or Square Regression) and SST(Sum of Square Total) with the following coding? I have confirmed that SSR and SST are derived.

```
postf <- bayesglm.fit(xx,y, family = gaussian(), prior.mean = c(8663265, 325.9304, 1435.758, -4388.022, -1973.862, 2686.825, 1830.709, -442.933, 762.1138), prior.df = Inf)
summary(postf)
postf$coeff
postf$fit
postf$y
postf$res

SSE <- cumsum((postf$res)^2) #SSE(Sum of Square Error)
SST <- cumsum((postf$y-mean(postf$y))^2) #SST(Sum of Square Total)
SSR <- cumsum((postf$fit-mean(postf$y))^2) #SSR(Sum or Square Regression)

print(SST)
print(SSR)
```

Question 2. The number of variables in the Bayesian multiple regression analysis Estimation Function that I intend to execute is nine, and the prior-mean of the nine variables have been replaced by vector type(c()) accordingly. However, when substituting the prior-mean, the error "invalid length for prior.mean" appears. In this case, is it impossible to proceed with Bayesian estimates? Or is there another way?
```
> postf <- bayesglm.fit(xx,y, family = gaussian(), prior.mean = c(8663265, 325.9304, 1435.758, -4388.022, -1973.862, 2686.825, 1830.709, -442.933, 762.1138))
Error in bayesglm.fit(xx, y, family = gaussian(), prior.mean = c(8663265,  : 
  invalid length for prior.mean
```

**Comment by suyusung** [comment]
For Question 1, you can get R2 as lm does.  Or just get pseudo R2 by comparing the deviance between the null model and the saturated model.

For Question 2, does the count nine included the intercept?  If so, you should take it out as the prior.mean is the prior means for the covariates.  There is   prior.mean.for.intercept for the intercept.

**Comment by yj-kim-00** [comment]
First of all, thank you for your answer to question 1.
In question two, my variables are nine, and I have one intercept. Thus, the Bayesian Multiple Regression Analysis through "bayesglm" has been implemented (attached photo), but not only in Estimates through "bayesglm.fit". In this case, what's the cause?

```
xx=matrix(c(x1,x2,x3,x4,x5,x6,x7,x8,x9), nc=9)
```

**Comment by suyusung** [comment]
I guess you need to specify intercept = FALSE in bayesglm.fit.  This is because if you use bayesglm.fit directly, you will need to put 1's in your xx matrix if you want to estimate intercepts.  This is the default of bayesglm.fit.  If you just provide an xx matrix without 1's, which in your case is a N*9 matrix, then you will need to set intercept = FALSE.  Otherwise, just input x as  cbind(1, xx) .
