### ISSUE TITLE
Horseshoe prior?

### ISSUE THREAD

**Issue by bachlaw** [suyusung/arm#2]
Yu Sung,

Any chance we could get a horseshoe prior added to bayesglm? Vincent Dorie graciously did something similar for blme, but it would also be great to have arm offer this option too.  Thanks much.

Here is Vincent's addition: https://github.com/vdorie/blme/issues/3

**Comment by suyusung** [comment]
I don't think you can.  But I guess you can make the suggestion to stan_glm in the rstanarm.
