### ISSUE TITLE
Estimation Result depending on order of covariates?

### ISSUE THREAD

**Issue by AndreWal** [suyusung/arm#3]
Dear Yu-Sung Su, 

I noticed recently a rather strange behaviour of the bayesglm-function. More specifically, it seems that the results of the bayesglm-function depend on the order of covariates in the formula argument. To give an example in R:

library(arm)

data(lalonde)

m1 <- bayesglm(married~age+educ, lalonde, family = binomial("logit"))
summary(m1)
m2 <- bayesglm(married~educ+age, lalonde, family = binomial("logit"))
summary(m2)

In the example, the differences of the point estimate and  standard error differ only slightly. However, for other datasets I use in my daily work, I noticed that the differences can become quite large. Could there be something wrong with the function?

Best,
André

**Comment by suyusung** [comment]
Hi this is indeed a bug.  I have fixed it!  Thank you!
