### ISSUE TITLE
small typo in standardize example

### ISSUE THREAD

**Issue by gjabel** [suyusung/arm#8]
When creating the `M1.2` objects in the example code would it make more sense to use the standardize function on the original model `M1` rather than the model that has already used `rescale` (`M1.1`)? i.e. 
    `M1.2 <- standardize(M1.1)`
should be 
    `M1.2 <- standardize(M1)`
in both examples

**Comment by suyusung** [comment]
Hi thanks for notify the issue.  I have fixed this.
